### ISSUE TITLE
Getting undefined method error on Rails 6

### ISSUE THREAD

**Issue by mikenath223** [vergilet/repost#13]
It throws undefined method error on my Rails 6.

I am presently trying to use it for my Rails Api
Steps I took:
1. add to gemfile:
`gem 'repost'`
2. Run `bundle install`
3. Controller structure:

```
module Api::V1
  class UsersController < ApplicationController
    ...
   
       def create
      @user = User.new(user_create_params)
      if @user.save
        repost(api_v1_user_token_path, params: { auth: request.params[:user] })
      else
        json_response(@user.errors.full_messages, :bad_request)
      end
    end

  end
end
```

It however throws an error: `NoMethodError (undefined method 'repost' for #<Api::V1::UsersController:0x0000558eeb152d98>)`

**Comment by vergilet** [comment]
@mikenath223 currently you can try to use
```
  Repost::Senpai.perform(api_v1_user_token_path, params: { auth: request.params[:user] })
```

It doesn't work yet with `repost` method because that method included only to `ActionController::Base` but not to `ActionController::API`. Working on the solution.

**Comment by vergilet** [comment]
Closing
