### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by LalaDK** [vergilet/repost#2]
Hello,
First off, thank you for a very nice gem!

We are running an older Ruby version; 2.3.8 in our production environment, and the gem breaks as the method String.concat does not allow for multiple arguments in 2.3.8. 

In senpai.rb@24 the code states: form_head.concat(compiled_body, form_footer)

That results in an error: "ArgumentError: wrong number of arguments (given 2, expected 1)" in Ruby 2.3.8.

The gem works fine in my development environment as I use a higher Ruby version. 

I think I'll be able to make a fix if wanted. 

Kind regards 
Mads

**Comment by vergilet** [comment]
@LalaDK, thanks for the issue. 
 
I have improved the gem for ruby version < 2.4, which do not have multiple concat.

Please update gem to version `0.2.8`.
Thanks!

**Comment by vergilet** [comment]
@LalaDK, thanks for help.
Closing this!
