### ISSUE TITLE
Partial string sent as param value when the params value has a quoted string in the value

### ISSUE THREAD

**Issue by supiash1** [vergilet/repost#26]
Hi,
Thank you for the gem, we have recently encountered an issue and our tests were intermittently failing while using the gem for an use case when there is a quoted string in the param value the partial string is being sent
<img width="497" alt="Screenshot 2022-07-19 at 21 24 53" src="https://user-images.githubusercontent.com/18370888/179841727-cf2856d9-aa57-48c7-8aa7-ebbe4f54c03c.png">
I have tried to create pr to fix the issue but looks like i do not have permission
this is how i would go about fixing, 
<img width="512" alt="Screenshot 2022-07-19 at 21 26 34" src="https://user-images.githubusercontent.com/18370888/179842019-c3f78395-85a0-40df-9603-8626aa132195.png">
<img width="932" alt="Screenshot 2022-07-19 at 21 26 27" src="https://user-images.githubusercontent.com/18370888/179842244-1e31b26a-4d3a-4df9-8cf7-3548d0a8652c.png">
could you consider this changes and let me know your opinion

**Comment by vergilet** [comment]
Hi @supiash1 !

Thanks for using gem and for your idea to fix the problem with quotes!

With your solution I afraid the final html form will contain:
```
value="Tuan O&quot;Keefe"
```
and that will require additional unescaping on receiver side.

So I came up with the another solution.

I have prepared a branch with it: [vergilet/repost#27](vergilet/repost#27)
You can verify it by using branch name in your Gemfile:

```ruby
gem 'repost', github: 'vergilet/repost', branch: 'escape-quoted-strings'
```

Please let me know if it works for you.
Thanks!

**Comment by vergilet** [comment]
@supiash1 gem version 0.4.0 has been released.
Please let me know if it works for you.
Feel free to close the issue if everything OK.
Have a nice day!
