### ISSUE TITLE
Deprecation Warning in Rails 6

### ISSUE THREAD

**Issue by aangott** [vergilet/repost#7]
Thanks for making this super-handy gem!

Just a heads up that I'm seeing a deprecation warning after adding `repost` to a Rails 6 app. The warning shows up at the beginning of the rspec test suite.  Here it is:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```

It appears that the cause of this warning is line 2 in `lib/repost/extend_controller.rb`.

**Comment by vergilet** [comment]
Hi @aangott!
Thanks for detecting this problem. Nice work!

I have already prepared a fix for that but I will need you help to confirm that the solution works.
It would be great if you can check it on your project, branch with fixes - `7-deprecation-rails-6`

Just change in your Gemfile:
```ruby
gem 'repost'
```
to:
```ruby
gem 'repost', github: 'vergilet/repost', branch: '7-deprecation-rails-6'
```
and try again to reproduce the "warnings" during the `rspec`.
After your confirmation that it works I will release build `0.3.1` on rubygems.

Looking forward to your answer.

**Comment by vergilet** [comment]
@aangott,

Changes are already in `master` and on rubygems.
You can update `repost` gem to version `0.3.1`.

Thanks!
